--- 
- 
  hosts: web1.rhpds.opentlc.com
  name: "This sets up an httpd webserver"
    tasks: 
    - 
      name: "Install the httpd rpm"
      yum: name=httpd
    - 
      name: "start the httpd service"
      service: "name=httpd state=started"
    - 
      firewalld: "service=http permanent=true state=enabled"
      name: "Open port 80"
    - 
      name: "start the firwalld service"
      service: "name=firewalld state=restarted"
